# Generated by Django 5.2.6 on 2026-04-14 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('email_verificado', models.BooleanField(default=False, help_text='Indica si el email fue verificado.')),
                ('acepta_terminos', models.BooleanField(default=False, help_text='Aceptación de términos y condiciones.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.OneToOneField(blank=True, help_text='Cliente comercial vinculado, si existe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_web', to='clientes.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_web', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente web',
                'verbose_name_plural': 'Clientes web',
                'ordering': ['-id'],
            },
        ),
    ]
