# Generated by Django 5.2.6 on 2026-07-25 06:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_plazo_cobro_dias'),
        ('presupuestos', '0001_initial'),
        ('remitos', '0003_alter_remitoadjunto_options_alter_remito_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_factura', models.DateField()),
                ('tipo_comprobante', models.CharField(choices=[('factura_a', 'Factura A'), ('factura_b', 'Factura B'), ('factura_c', 'Factura C'), ('nota_debito', 'Nota de débito'), ('otro', 'Otro')], max_length=30)),
                ('punto_venta', models.PositiveIntegerField()),
                ('numero_factura', models.PositiveBigIntegerField()),
                ('orden_compra', models.CharField(blank=True, max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('medio_envio', models.CharField(blank=True, choices=[('correo_electronico', 'Correo electrónico'), ('papel', 'Papel'), ('portal', 'Portal'), ('whatsapp', 'WhatsApp'), ('otro', 'Otro')], max_length=30)),
                ('observacion_envio', models.TextField(blank=True)),
                ('plazo_cobro_dias', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_estimada_cobro', models.DateField(blank=True, null=True)),
                ('fecha_estimada_manual', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cobranza', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cobranza_creadas', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cobranza_enviadas', to=settings.AUTH_USER_MODEL)),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cobranza', to='presupuestos.presupuesto')),
                ('remitos', models.ManyToManyField(blank=True, related_name='facturas_cobranza', to='remitos.remito')),
            ],
            options={
                'verbose_name': 'Factura de cobranza',
                'verbose_name_plural': 'Facturas de cobranza',
                'ordering': ['-fecha_factura', '-id'],
                'permissions': [('registrar_cobro', 'Puede registrar cobros'), ('agregar_seguimiento', 'Puede agregar seguimientos de cobranza')],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('medio_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('retencion', 'Retención'), ('compensacion', 'Compensación'), ('otro', 'Otro')], max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_registrados', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='cobranzas.facturacobranza')),
            ],
            options={
                'ordering': ['-fecha_cobro', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('reclamo', 'Reclamo'), ('contacto', 'Contacto'), ('promesa_pago', 'Promesa de pago'), ('confirmacion_recepcion', 'Confirmación de recepción'), ('otro', 'Otro')], max_length=30)),
                ('detalle', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='cobranzas.facturacobranza')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_cobranza_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='facturacobranza',
            index=models.Index(fields=['cliente', 'fecha_factura'], name='cobranzas_f_cliente_faa019_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacobranza',
            index=models.Index(fields=['fecha_estimada_cobro'], name='cobranzas_f_fecha_e_57c495_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacobranza',
            index=models.Index(fields=['tipo_comprobante', 'punto_venta', 'numero_factura'], name='cobranzas_f_tipo_co_860132_idx'),
        ),
        migrations.AddConstraint(
            model_name='facturacobranza',
            constraint=models.UniqueConstraint(fields=('tipo_comprobante', 'punto_venta', 'numero_factura'), name='cobranzas_factura_identificacion_unica'),
        ),
        migrations.AddConstraint(
            model_name='facturacobranza',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='cobranzas_factura_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='facturacobranza',
            constraint=models.CheckConstraint(condition=models.Q(('plazo_cobro_dias__gte', 0)), name='cobranzas_factura_plazo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cobro',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='cobranzas_cobro_importe_positivo'),
        ),
    ]
