# Generated by Django 5.2.6 on 2026-07-25 06:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacobranza',
            name='plazo_cobro_dias',
            field=models.PositiveIntegerField(blank=True, default=None, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['fecha_cobro'], name='cobranzas_c_fecha_c_e0c9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['factura', 'fecha_cobro'], name='cobranzas_c_factura_a04665_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientocobranza',
            index=models.Index(fields=['factura', 'fecha'], name='cobranzas_s_factura_f4cbde_idx'),
        ),
    ]
