# Generated by Django 5.2.6 on 2026-07-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0002_alter_facturacobranza_plazo_cobro_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacobranza',
            name='comprobante_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='cobranzas.facturacobranza'),
        ),
        migrations.AlterField(
            model_name='facturacobranza',
            name='tipo_comprobante',
            field=models.CharField(choices=[('factura_a', 'Factura A'), ('factura_b', 'Factura B'), ('factura_c', 'Factura C'), ('nota_debito', 'Nota de débito'), ('nota_credito', 'Nota de crédito'), ('otro', 'Otro')], max_length=30),
        ),
    ]
