# Generated by Django 5.2.6 on 2025-09-26 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ambos', 'Ambos')], default='ambos', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre'], name='impuestos_i_nombre_5e9a7b_idx')],
            },
        ),
    ]
