# Generated by Django 5.2.6 on 2025-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impuestos', '0002_impuesto_actualizado_impuesto_creado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impuesto',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Impuestos'},
        ),
        migrations.AddField(
            model_name='impuesto',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
