# Generated by Django 5.2.6 on 2026-04-14 03:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_alter_servicio_costo_base_alter_servicio_precio_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('contactado', 'Contactado'), ('confirmado', 'Confirmado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones_cliente', models.TextField(blank=True, default='', help_text='Observaciones escritas por el cliente desde la web.')),
                ('observaciones_internas', models.TextField(blank=True, default='', help_text='Notas internas del equipo.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente comercial asociado, si existe.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_web', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('mercaderia', 'Mercadería'), ('servicio', 'Servicio')], max_length=20)),
                ('nombre_snapshot', models.CharField(help_text='Nombre del producto/servicio al momento del pedido.', max_length=255)),
                ('codigo_snapshot', models.CharField(blank=True, default='', help_text='Código o SKU al momento del pedido.', max_length=50)),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_items', to='productos.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_items', to='productos.servicio')),
            ],
            options={
                'verbose_name': 'Ítem de pedido',
                'verbose_name_plural': 'Ítems de pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedidos_ped_estado_20cbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['creado'], name='pedidos_ped_creado_efe226_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoitem',
            index=models.Index(fields=['tipo_item'], name='pedidos_ped_tipo_it_f10ef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('producto__isnull', False), ('servicio__isnull', True)), models.Q(('producto__isnull', True), ('servicio__isnull', False)), _connector='OR'), name='pedido_item_producto_o_servicio'),
        ),
    ]
