# Generated by Django 5.2.6 on 2026-04-14 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('web_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_web',
            field=models.ForeignKey(blank=True, help_text='Cliente autenticado de la web.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='web_clientes.clienteweb'),
        ),
    ]
