# Generated by Django 5.2.6 on 2026-06-04 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0003_pedido_flags_stock'),
        ('web_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_ped_estado_20cbc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_ped_creado_efe226_idx',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_web', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_web',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='web_clientes.clienteweb'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observaciones_cliente',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observaciones_internas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
