# Generated by Django 5.2.6 on 2025-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRES', 'Presupuesto')], default='PRES', max_length=10)),
                ('serie', models.CharField(default='00001', max_length=5)),
                ('numero', models.IntegerField(editable=False)),
                ('numero_inicial', models.IntegerField(default=1)),
                ('numero_final', models.IntegerField()),
                ('numero_comienzo', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'serie', 'numero'], name='comprobante_tipo_4b99eb_idx')],
                'unique_together': {('tipo', 'serie', 'numero')},
            },
        ),
    ]
