# Generated by Django 5.2.6 on 2025-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRES', 'Presupuesto')], default='PRES', max_length=10)),
                ('serie', models.CharField(default='00001', max_length=5)),
                ('numero', models.IntegerField(editable=False)),
                ('numero_inicial', models.IntegerField(default=1, help_text='Primer número autorizado del rango (ej: 1)')),
                ('numero_final', models.IntegerField(default=500, help_text='Último número autorizado actualmente (ej: 500)')),
                ('proximo_numero', models.IntegerField(default=1, help_text='Próximo número que se usará realmente. Ejemplo: Si el último presupuesto fue #49, aquí debe ir 50')),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'serie', 'numero'], name='comprobante_tipo_4b99eb_idx')],
                'unique_together': {('tipo', 'serie', 'numero')},
            },
        ),
    ]
