# Generated by Django 5.2.6 on 2025-12-08 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='cliente',
            field=models.CharField(blank=True, help_text='Destinatario/cliente del remito (obligatorio para REMI)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', help_text='Estado del comprobante', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobante',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales', null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='tipo',
            field=models.CharField(choices=[('PRES', 'Presupuesto'), ('REMI', 'Remito Interno')], default='PRES', max_length=10),
        ),
    ]
