# Generated by Django 5.2.6 on 2025-12-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0002_comprobante_cliente_comprobante_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='numero_final',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='numero_inicial',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='proximo_numero',
            field=models.IntegerField(default=1),
        ),
    ]
