# Generated by Django 5.2.6 on 2026-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_remove_comprobante_cliente_remove_comprobante_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobante',
            options={'verbose_name': 'Configuración de Numeración', 'verbose_name_plural': 'Configuraciones de Numeración'},
        ),
        migrations.RemoveIndex(
            model_name='comprobante',
            name='comprobante_tipo_4b99eb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='comprobante',
            unique_together={('tipo', 'serie')},
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='numero_final',
            field=models.IntegerField(help_text='Último número del rango'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='numero_inicial',
            field=models.IntegerField(default=1, help_text='Primer número del rango'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='proximo_numero',
            field=models.IntegerField(default=1, help_text='Próximo número a usar. Puede ajustarse manualmente si hubo documentos fuera del sistema.'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='serie',
            field=models.CharField(default='00001', help_text='Serie (punto de venta/sucursal)', max_length=5),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='tipo',
            field=models.CharField(choices=[('PRES', 'Presupuesto'), ('REMI', 'Remito Interno')], default='PRES', help_text='Tipo de comprobante que controla esta configuración', max_length=10),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['tipo', 'serie'], name='comprobante_tipo_04fcd0_idx'),
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='numero',
        ),
    ]
