# Generated by Django 5.2.6 on 2025-11-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Mi Empresa S.A.', max_length=200)),
                ('cuit', models.CharField(blank=True, default='', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('pagina_web', models.URLField(blank=True, default='')),
                ('logo_principal', models.ImageField(blank=True, help_text='Logo grande para encabezados de documentos', null=True, upload_to='config/logos/', verbose_name='Logo Principal (Header PDFs)')),
                ('logo_favicon', models.ImageField(blank=True, help_text='Icono pequeño para pestañas del navegador (16x16px o 32x32px)', null=True, upload_to='config/logos/', verbose_name='Favicon (Barra de direcciones)')),
                ('logo_tkinter', models.ImageField(blank=True, help_text='Logo para reemplazar icono por defecto de Tkinter', null=True, upload_to='config/logos/', verbose_name='Logo Tkinter (Interfaz Desktop)')),
                ('imagen_publicitaria_1', models.ImageField(blank=True, help_text='Imagen pequeña para pie de página (ej: marca 1)', null=True, upload_to='config/publicidad/', verbose_name='Imagen Publicitaria 1')),
                ('imagen_publicitaria_2', models.ImageField(blank=True, help_text='Imagen pequeña para pie de página (ej: marca 2)', null=True, upload_to='config/publicidad/', verbose_name='Imagen Publicitaria 2')),
                ('imagen_publicitaria_3', models.ImageField(blank=True, help_text='Imagen pequeña para pie de página (ej: marca 3)', null=True, upload_to='config/publicidad/', verbose_name='Imagen Publicitaria 3')),
                ('condiciones_comerciales', models.TextField(default='Precios expresados en pesos Argentinos\nPlazo de entrega: Inmediata\nForma de Pago: 30 días\nMantenimiento de oferta: 15 días')),
                ('iva_por_defecto', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('dias_validez_presupuesto', models.PositiveIntegerField(default=30)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares')], default='ARS', max_length=10)),
                ('pais', models.CharField(default='Argentina', max_length=50)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
    ]
