# Generated by Django 5.2.6 on 2025-11-12 17:18

import configuracion.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_1_alto',
            field=models.PositiveIntegerField(default=300, help_text='Alto máximo en píxeles', verbose_name='Alto Imagen 1 (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_1_ancho',
            field=models.PositiveIntegerField(default=400, help_text='Ancho máximo en píxeles', verbose_name='Ancho Imagen 1 (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_1_proporcion',
            field=models.BooleanField(default=True, help_text='Mantener relación de aspecto original', verbose_name='Mantener proporción'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_2_alto',
            field=models.PositiveIntegerField(default=300, help_text='Alto máximo en píxeles', verbose_name='Alto Imagen 2 (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_2_ancho',
            field=models.PositiveIntegerField(default=400, help_text='Ancho máximo en píxeles', verbose_name='Ancho Imagen 2 (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_2_proporcion',
            field=models.BooleanField(default=True, help_text='Mantener relación de aspecto original', verbose_name='Mantener proporción'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_3_alto',
            field=models.PositiveIntegerField(default=300, help_text='Alto máximo en píxeles', verbose_name='Alto Imagen 3 (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_3_ancho',
            field=models.PositiveIntegerField(default=400, help_text='Ancho máximo en píxeles', verbose_name='Ancho Imagen 3 (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_3_proporcion',
            field=models.BooleanField(default=True, help_text='Mantener relación de aspecto original', verbose_name='Mantener proporción'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_favicon_alto',
            field=models.PositiveIntegerField(default=32, help_text='Alto máximo en píxeles', verbose_name='Alto Favicon (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_favicon_ancho',
            field=models.PositiveIntegerField(default=32, help_text='Ancho máximo en píxeles', verbose_name='Ancho Favicon (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_favicon_proporcion',
            field=models.BooleanField(default=True, help_text='Mantener relación de aspecto original', verbose_name='Mantener proporción'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_principal_alto',
            field=models.PositiveIntegerField(default=600, help_text='Alto máximo en píxeles', verbose_name='Alto Logo Principal (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_principal_ancho',
            field=models.PositiveIntegerField(default=800, help_text='Ancho máximo en píxeles', verbose_name='Ancho Logo Principal (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_principal_proporcion',
            field=models.BooleanField(default=True, help_text='Mantener relación de aspecto original', verbose_name='Mantener proporción'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_tkinter_alto',
            field=models.PositiveIntegerField(default=256, help_text='Alto máximo en píxeles', verbose_name='Alto Logo Tkinter (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_tkinter_ancho',
            field=models.PositiveIntegerField(default=256, help_text='Ancho máximo en píxeles', verbose_name='Ancho Logo Tkinter (px)'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='logo_tkinter_proporcion',
            field=models.BooleanField(default=True, help_text='Mantener relación de aspecto original', verbose_name='Mantener proporción'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_1',
            field=configuracion.fields.RedimensionableImageField(blank=True, help_text='Imagen pequeña para pie de página', null=True, upload_to='config/publicidad/', verbose_name='Imagen Publicitaria 1'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_2',
            field=configuracion.fields.RedimensionableImageField(blank=True, help_text='Imagen pequeña para pie de página', null=True, upload_to='config/publicidad/', verbose_name='Imagen Publicitaria 2'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='imagen_publicitaria_3',
            field=configuracion.fields.RedimensionableImageField(blank=True, help_text='Imagen pequeña para pie de página', null=True, upload_to='config/publicidad/', verbose_name='Imagen Publicitaria 3'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='logo_favicon',
            field=configuracion.fields.RedimensionableImageField(blank=True, help_text='Icono pequeño para pestañas del navegador', null=True, upload_to='config/logos/', verbose_name='Favicon (Barra de direcciones)'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='logo_principal',
            field=configuracion.fields.RedimensionableImageField(blank=True, help_text='Logo grande para encabezados de documentos', null=True, upload_to='config/logos/', verbose_name='Logo Principal (Header PDFs)'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='logo_tkinter',
            field=configuracion.fields.RedimensionableImageField(blank=True, help_text='Logo para reemplazar icono por defecto de Tkinter', null=True, upload_to='config/logos/', verbose_name='Logo Tkinter (Interfaz Desktop)'),
        ),
    ]
