# Generated by Django 5.2.6 on 2025-11-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracionglobal_imagen_publicitaria_1_alto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='descripcion_sistema',
            field=models.CharField(default='Sistema de Gestión Comercial', help_text='Texto descriptivo que aparece debajo del nombre', max_length=100, verbose_name='Descripción del Sistema'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='nombre_fantasia',
            field=models.CharField(default='Empresa de Servicios', help_text='Nombre comercial que se muestra en el login', max_length=200, verbose_name='Nombre Fantasía'),
        ),
    ]
