# Generated by Django 5.2.6 on 2025-12-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuracionglobal_descripcion_sistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='proximo_numero_presupuesto',
            field=models.IntegerField(default=1, help_text='Próximo número que se usará para presupuestos. Se sincroniza automáticamente con Comprobante → Próximo número', verbose_name='Próximo número de presupuesto'),
        ),
    ]
