# Generated by Django 5.2.6 on 2025-12-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_configuracionglobal_proximo_numero_presupuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionglobal',
            options={'ordering': ['-activo', '-creado'], 'verbose_name': 'Configuración Global', 'verbose_name_plural': 'Configuraciones Globales'},
        ),
        migrations.RemoveField(
            model_name='configuracionglobal',
            name='proximo_numero_presupuesto',
        ),
    ]
