# Generated by Django 5.2.6 on 2026-06-04 23:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0007_remove_producto_foto_remove_producto_plano_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador corto, ej. TALLER, DEPOSITO_1.', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PedidoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, editable=False, help_text='Número correlativo legible (se asigna automáticamente).', null=True, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('en_proceso', 'En proceso'), ('derivado', 'Derivado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_internos', to=settings.AUTH_USER_MODEL)),
                ('sector_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_origen', to='pedidos_internos.sector')),
            ],
            options={
                'verbose_name': 'Pedido interno',
                'verbose_name_plural': 'Pedidos internos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoInternoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Texto libre del pedido (o etiqueta del producto/servicio).', max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('observacion', models.TextField(blank=True, default='', help_text="Aclaración del renglón, ej. 'SKF preferentemente'.")),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos_internos.pedidointerno')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_interno_detalles', to='productos.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_interno_detalles', to='productos.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de pedido interno',
                'verbose_name_plural': 'Detalles de pedido interno',
            },
        ),
        migrations.CreateModel(
            name='PedidoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('recibido', 'Recibido'), ('leido', 'Leído'), ('derivado', 'Derivado'), ('en_proceso', 'En proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('comentario', 'Comentario')], max_length=20)),
                ('detalle', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pedidos_internos.pedidointerno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_pedido_interno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de pedido',
                'verbose_name_plural': 'Movimientos de pedido',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_responsable', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='pedidos_internos.pedidointerno')),
                ('sector_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_destino', to='pedidos_internos.sector')),
            ],
            options={
                'verbose_name': 'Destino de pedido',
                'verbose_name_plural': 'Destinos de pedido',
                'ordering': ['pedido', 'sector_destino'],
                'unique_together': {('pedido', 'sector_destino')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='pedidos_internos.sector')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario por sector',
                'verbose_name_plural': 'Usuarios por sector',
                'ordering': ['sector', 'usuario'],
                'unique_together': {('usuario', 'sector')},
            },
        ),
    ]
