# Generated by Django 5.2.6 on 2026-06-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_internos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidointernodetalle',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio'), ('otro', 'Otro')], default='producto', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidointernodetalle',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text="Descripción del renglón. Obligatoria para tipo 'Otro'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidointernodetalle',
            name='observacion',
            field=models.TextField(blank=True, default='', help_text='Aclaración adicional del renglón.'),
        ),
    ]
