# Generated by Django 5.2.6 on 2026-07-11 22:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


ACCIONES_CAMBIO_ESTADO = (
    'recibido',
    'en_proceso',
    'resuelto',
    'rechazado',
    'entregado',
)


def inicializar_fechas_destinos(apps, schema_editor):
    PedidoDestino = apps.get_model(
        'pedidos_internos',
        'PedidoDestino',
    )
    PedidoMovimiento = apps.get_model(
        'pedidos_internos',
        'PedidoMovimiento',
    )
    db_alias = schema_editor.connection.alias
    destinos = PedidoDestino.objects.using(db_alias)
    movimientos = PedidoMovimiento.objects.using(db_alias)

    cantidades_por_pedido = dict(
        destinos
        .values('pedido_id')
        .annotate(total=models.Count('id'))
        .values_list('pedido_id', 'total')
    )

    estados_por_destino = {}
    lecturas_por_destino = {}
    estados_por_pedido_unico = {}
    lecturas_por_pedido_unico = {}

    movimientos_relevantes = (
        movimientos
        .filter(accion__in=ACCIONES_CAMBIO_ESTADO + ('leido',))
        .values(
            'pedido_id',
            'destino_id',
            'accion',
            'fecha',
        )
        .iterator(chunk_size=2000)
    )

    for movimiento in movimientos_relevantes:
        destino_id = movimiento['destino_id']
        pedido_id = movimiento['pedido_id']
        accion = movimiento['accion']
        fecha = movimiento['fecha']

        if destino_id is not None:
            if accion == 'leido':
                fecha_actual = lecturas_por_destino.get(destino_id)
                if fecha_actual is None or fecha < fecha_actual:
                    lecturas_por_destino[destino_id] = fecha
            else:
                fecha_actual = estados_por_destino.get(destino_id)
                if fecha_actual is None or fecha > fecha_actual:
                    estados_por_destino[destino_id] = fecha
            continue

        if cantidades_por_pedido.get(pedido_id) != 1:
            continue

        if accion == 'leido':
            fecha_actual = lecturas_por_pedido_unico.get(pedido_id)
            if fecha_actual is None or fecha < fecha_actual:
                lecturas_por_pedido_unico[pedido_id] = fecha
        else:
            fecha_actual = estados_por_pedido_unico.get(pedido_id)
            if fecha_actual is None or fecha > fecha_actual:
                estados_por_pedido_unico[pedido_id] = fecha

    destinos_a_actualizar = []

    for destino in destinos.all().iterator(chunk_size=1000):
        fecha_movimiento_estado = estados_por_destino.get(
            destino.pk,
        )
        fecha_movimiento_lectura = lecturas_por_destino.get(
            destino.pk,
        )

        # Los movimientos anteriores a esta migración no tenían destino.
        # Solo es seguro inferir su sector cuando el pedido tenía un único
        # PedidoDestino; en pedidos multidestino se usan los fallbacks.
        if cantidades_por_pedido.get(destino.pedido_id) == 1:
            if fecha_movimiento_estado is None:
                fecha_movimiento_estado = estados_por_pedido_unico.get(
                    destino.pedido_id,
                )

            if fecha_movimiento_lectura is None:
                fecha_movimiento_lectura = lecturas_por_pedido_unico.get(
                    destino.pedido_id,
                )

        if destino.leido and destino.fecha_leido is None:
            destino.fecha_leido = (
                fecha_movimiento_lectura
                if fecha_movimiento_lectura is not None
                else destino.creado
            )

        destino.fecha_estado = (
            fecha_movimiento_estado
            if fecha_movimiento_estado is not None
            else destino.fecha_leido or destino.creado
        )
        destino.actualizado = destino.fecha_estado
        destinos_a_actualizar.append(destino)

        if len(destinos_a_actualizar) >= 1000:
            destinos.bulk_update(
                destinos_a_actualizar,
                ['fecha_leido', 'fecha_estado', 'actualizado'],
                batch_size=1000,
            )
            destinos_a_actualizar = []

    if destinos_a_actualizar:
        destinos.bulk_update(
            destinos_a_actualizar,
            ['fecha_leido', 'fecha_estado', 'actualizado'],
            batch_size=1000,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_internos', '0002_pedidointernodetalle_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoReglaSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hito_origen', models.CharField(choices=[('enviado', 'Enviado'), ('leido', 'Leído'), ('recibido', 'Recibido'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('hito_destino', models.CharField(choices=[('enviado', 'Enviado'), ('leido', 'Leído'), ('recibido', 'Recibido'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('horas_limite', models.DecimalField(decimal_places=2, help_text='Cantidad máxima de horas corridas permitidas para completar la transición.', max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla SLA de pedido interno',
                'verbose_name_plural': 'Reglas SLA de pedidos internos',
                'ordering': ['sector__codigo', 'hito_origen', 'hito_destino'],
            },
        ),
        migrations.AlterModelOptions(
            name='pedidodestino',
            options={'ordering': ['-creado'], 'verbose_name': 'Destino de pedido', 'verbose_name_plural': 'Destinos de pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedidomovimiento',
            options={'ordering': ['fecha', 'id'], 'verbose_name': 'Movimiento de pedido interno', 'verbose_name_plural': 'Movimientos de pedidos internos'},
        ),
        migrations.AlterUniqueTogether(
            name='pedidodestino',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedidodestino',
            name='actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodestino',
            name='fecha_estado',
            field=models.DateTimeField(blank=True, help_text='Fecha desde la cual el destino se encuentra en el estado actual.', null=True),
        ),
        migrations.AddField(
            model_name='pedidodestino',
            name='leido_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que abrió por primera vez el destino.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_leidos_primero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidomovimiento',
            name='destino',
            field=models.ForeignKey(blank=True, db_index=False, help_text='Destino afectado por la acción. Puede quedar vacío en movimientos generales del pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='pedidos_internos.pedidodestino'),
        ),
        migrations.AddField(
            model_name='pedidomovimiento',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedidomovimiento',
            name='estado_nuevo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedidomovimiento',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Información complementaria estructurada, como sectores de una derivación u otros datos de auditoría.'),
        ),
        migrations.AddField(
            model_name='pedidomovimiento',
            name='sla_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidomovimiento',
            name='sla_duracion_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidomovimiento',
            name='sla_limite_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pedidomovimiento',
            name='sla_vencido',
            field=models.BooleanField(blank=True, help_text='Null significa que el movimiento no fue evaluado o que no tenía una regla SLA aplicable.', null=True),
        ),
        migrations.AlterField(
            model_name='pedidodestino',
            name='leido',
            field=models.BooleanField(default=False, help_text='Indica si algún usuario del sector abrió el detalle.'),
        ),
        migrations.AlterField(
            model_name='pedidodestino',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Referente principal del sector. No bloquea la intervención de otros miembros activos del mismo sector.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidointerno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('parcial', 'Finalizado parcialmente'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('recibido', 'Recibido'), ('derivado', 'Derivado'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', help_text='Estado global calculado a partir de los destinos. No debe modificarse directamente.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidointerno',
            name='numero',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidomovimiento',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('enviado', 'Enviado'), ('leido', 'Leído'), ('recibido', 'Recibido'), ('responsable_asignado', 'Responsable asignado'), ('en_proceso', 'En proceso'), ('comentario', 'Comentario'), ('derivado', 'Derivado'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], max_length=30),
        ),
        migrations.RunPython(
            inicializar_fechas_destinos,
            migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "pedidos_internos_pedidodestino" '
                        'ALTER COLUMN "actualizado" SET NOT NULL'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "pedidos_internos_pedidodestino" '
                        'ALTER COLUMN "actualizado" DROP NOT NULL'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "pedidos_internos_pedidodestino" '
                        'ALTER COLUMN "fecha_estado" SET NOT NULL'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "pedidos_internos_pedidodestino" '
                        'ALTER COLUMN "fecha_estado" DROP NOT NULL'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='pedidodestino',
                    name='actualizado',
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name='pedidodestino',
                    name='fecha_estado',
                    field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha desde la cual el destino se encuentra en el estado actual.'),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='pedidodestino',
            index=models.Index(fields=['sector_destino', 'estado'], name='pint_dest_sector_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidodestino',
            index=models.Index(fields=['sector_destino', 'leido'], name='pint_dest_sector_leido_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidodestino',
            index=models.Index(fields=['responsable', 'estado'], name='pint_dest_resp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidointerno',
            index=models.Index(fields=['estado', 'prioridad'], name='pint_pedido_estado_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidointerno',
            index=models.Index(fields=['sector_origen', 'creado'], name='pint_pedido_origen_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidointerno',
            index=models.Index(fields=['solicitante', 'creado'], name='pint_pedido_solic_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidomovimiento',
            index=models.Index(fields=['pedido', 'fecha'], name='pint_mov_pedido_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidomovimiento',
            index=models.Index(fields=['destino', 'fecha'], name='pint_mov_destino_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidomovimiento',
            index=models.Index(fields=['accion', 'fecha'], name='pint_mov_accion_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidodestino',
            constraint=models.UniqueConstraint(fields=('pedido', 'sector_destino'), name='unique_pedido_sector_destino'),
        ),
        migrations.AddField(
            model_name='pedidoreglasla',
            name='sector',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_sla_pedidos_internos', to='pedidos_internos.sector'),
        ),
        migrations.AddConstraint(
            model_name='pedidoreglasla',
            constraint=models.UniqueConstraint(fields=('sector', 'hito_origen', 'hito_destino'), name='unique_regla_sla_sector_transicion'),
        ),
        migrations.AddConstraint(
            model_name='pedidoreglasla',
            constraint=models.CheckConstraint(condition=models.Q(('horas_limite__gt', 0)), name='regla_sla_horas_limite_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='pedidoreglasla',
            constraint=models.CheckConstraint(condition=models.Q(('hito_origen', models.F('hito_destino')), _negated=True), name='regla_sla_hitos_distintos'),
        ),
    ]
