# Generated by Django 5.2.6 on 2025-12-04 02:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('comprobantes', '0001_initial'),
        ('productos', '0002_alter_servicio_costo_base_alter_servicio_precio_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('condiciones_comerciales', models.TextField(blank=True, null=True)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_anulados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comprobantes.comprobante')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to='presupuestos/adjuntos/%Y/%m/%d/', verbose_name='Archivo adjunto')),
                ('tipo', models.CharField(choices=[('plano', '📐 Planos (PDF, DWG)'), ('foto', '🖼️ Fotos (referencia, ubicación)'), ('diagrama', '📊 Diagramas técnicos'), ('contrato', '📝 Contratos/Especificaciones'), ('comunicacion', '💬 Comunicaciones relevantes'), ('otro', '📎 Otros')], default='otro', help_text='Clasificación del archivo para organización', max_length=20, verbose_name='Tipo de archivo')),
                ('nombre_original', models.CharField(help_text='Nombre original al momento de subir', max_length=255, verbose_name='Nombre original del archivo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del contenido y propósito del archivo', max_length=1000, verbose_name='Descripción detallada')),
                ('tamaño', models.BigIntegerField(help_text='Tamaño del archivo en bytes', verbose_name='Tamaño en bytes')),
                ('extension', models.CharField(help_text='Extensión (pdf, jpg, dwg, etc.)', max_length=10, verbose_name='Extensión del archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('es_publico', models.BooleanField(default=True, help_text='Si es False, solo usuarios autorizados pueden verlo', verbose_name='¿Es público?')),
                ('version', models.PositiveIntegerField(default=1, help_text='Número de versión para revisiones', verbose_name='Versión del archivo')),
                ('checksum', models.CharField(blank=True, help_text='Hash para verificar integridad del archivo', max_length=64, verbose_name='Checksum MD5')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos específicos por tipo de archivo', verbose_name='Metadatos adicionales')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='presupuestos.presupuesto', verbose_name='Presupuesto relacionado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_adjuntos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de presupuesto',
                'verbose_name_plural': 'Adjuntos de presupuestos',
                'ordering': ['-fecha_subida', 'tipo', 'nombre_original'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.presupuesto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.servicio')),
            ],
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['comprobante'], name='presupuesto_comprob_465f53_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuestoadjunto',
            index=models.Index(fields=['presupuesto', 'tipo'], name='presupuesto_presupu_f52a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuestoadjunto',
            index=models.Index(fields=['presupuesto', 'fecha_subida'], name='presupuesto_presupu_663eec_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuestoadjunto',
            index=models.Index(fields=['tipo', 'es_publico'], name='presupuesto_tipo_d162f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='presupuestoadjunto',
            constraint=models.CheckConstraint(condition=models.Q(('tamaño__gte', 0)), name='tamaño_archivo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='presupuestoitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('producto__isnull', False), ('servicio__isnull', True)), models.Q(('producto__isnull', True), ('servicio__isnull', False)), _connector='OR'), name='presupuesto_item_producto_or_servicio'),
        ),
    ]
