# Generated by Django 5.2.6 on 2025-09-26 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('comprobantes', '0001_initial'),
        ('presupuestos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='presupuesto',
            name='presupuesto_numero_b43ca5_idx',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='numero',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='comprobante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comprobantes.comprobante'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='condiciones_comerciales',
            field=models.TextField(default='Precios expresados en pesos Argentinos\nPlazo de entrega: Inmediata\nForma de Pago: 30 días\nMantenimiento de oferta: 15 días'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='iva_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['comprobante'], name='presupuesto_comprob_465f53_idx'),
        ),
    ]
