# Generated by Django 5.2.6 on 2025-09-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_remove_presupuesto_presupuesto_numero_b43ca5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
