# Generated by Django 5.2.6 on 2025-09-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
        ('presupuestos', '0003_presupuesto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comprobantes.comprobante'),
        ),
    ]
