# Generated by Django 5.2.6 on 2025-11-10 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_presupuesto_numero_alter_presupuesto_comprobante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='PresupuestoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to='presupuestos/adjuntos/%Y/%m/%d/', verbose_name='Archivo adjunto')),
                ('tipo', models.CharField(choices=[('plano', '📐 Planos (PDF, DWG)'), ('foto', '🖼️ Fotos (referencia, ubicación)'), ('diagrama', '📊 Diagramas técnicos'), ('contrato', '📝 Contratos/Especificaciones'), ('comunicacion', '💬 Comunicaciones relevantes'), ('otro', '📎 Otros')], default='otro', help_text='Clasificación del archivo para organización', max_length=20, verbose_name='Tipo de archivo')),
                ('nombre_original', models.CharField(help_text='Nombre original al momento de subir', max_length=255, verbose_name='Nombre original del archivo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del contenido y propósito del archivo', max_length=1000, verbose_name='Descripción detallada')),
                ('tamaño', models.BigIntegerField(help_text='Tamaño del archivo en bytes', verbose_name='Tamaño en bytes')),
                ('extension', models.CharField(help_text='Extensión (pdf, jpg, dwg, etc.)', max_length=10, verbose_name='Extensión del archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('es_publico', models.BooleanField(default=True, help_text='Si es False, solo usuarios autorizados pueden verlo', verbose_name='¿Es público?')),
                ('version', models.PositiveIntegerField(default=1, help_text='Número de versión para revisiones', verbose_name='Versión del archivo')),
                ('checksum', models.CharField(blank=True, help_text='Hash para verificar integridad del archivo', max_length=64, verbose_name='Checksum MD5')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos específicos por tipo de archivo', verbose_name='Metadatos adicionales')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='presupuestos.presupuesto', verbose_name='Presupuesto relacionado')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_adjuntos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de presupuesto',
                'verbose_name_plural': 'Adjuntos de presupuestos',
                'ordering': ['-fecha_subida', 'tipo', 'nombre_original'],
                'indexes': [models.Index(fields=['presupuesto', 'tipo'], name='presupuesto_presupu_f52a1b_idx'), models.Index(fields=['presupuesto', 'fecha_subida'], name='presupuesto_presupu_663eec_idx'), models.Index(fields=['tipo', 'es_publico'], name='presupuesto_tipo_d162f5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tamaño__gte', 0)), name='tamaño_archivo_positivo')],
            },
        ),
    ]
