# Generated by Django 5.2.6 on 2025-11-10 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_alter_presupuesto_options_presupuestoadjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoadjunto',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_adjuntos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
    ]
