# Generated by Django 5.2.6 on 2025-11-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_alter_presupuestoadjunto_subido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='condiciones_comerciales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
