# Generated by Django 5.2.4 on 2025-11-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_alter_presupuesto_condiciones_comerciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
    ]
