# Generated by Django 5.2.6 on 2025-12-08 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='00001', max_length=5)),
                ('numero', models.IntegerField()),
                ('cliente', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=200, verbose_name='Desde')),
                ('destino', models.CharField(blank=True, max_length=200, verbose_name='Hacia')),
                ('presupuesto_relacionado', models.CharField(blank=True, max_length=100, verbose_name='Presupuesto relacionado')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, verbose_name='Referencia (Licitación/Orden de compra)')),
                ('numero_referencia', models.CharField(blank=True, max_length=50, verbose_name='N° de referencia')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remito',
                'verbose_name_plural': 'Remitos',
                'ordering': ['-fecha_emision', '-numero'],
                'unique_together': {('serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemRemito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(default='UNIDAD', max_length=20, verbose_name='Unidad')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('orden', models.IntegerField(default=0)),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='remitos.remito')),
            ],
            options={
                'verbose_name': 'Item de Remito',
                'verbose_name_plural': 'Items de Remito',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
