# Generated by Django 5.2.6 on 2025-12-10 00:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_remove_comprobante_cliente_remove_comprobante_estado_and_more'),
        ('remitos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemremito',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Item de remito', 'verbose_name_plural': 'Items de remito'},
        ),
        migrations.AlterModelOptions(
            name='remito',
            options={'ordering': ['-id'], 'verbose_name': 'Remito', 'verbose_name_plural': 'Remitos'},
        ),
        migrations.RenameField(
            model_name='remito',
            old_name='actualizado_en',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='remito',
            old_name='creado_en',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='remito',
            old_name='observaciones_generales',
            new_name='observaciones',
        ),
        migrations.AlterUniqueTogether(
            name='remito',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='remito',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remitos_anulados', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='remito',
            name='comprobante',
            field=models.ForeignKey(default=2, help_text='Configuración de numeración para remitos', limit_choices_to={'tipo': 'REMI'}, on_delete=django.db.models.deletion.PROTECT, to='comprobantes.comprobante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remito',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remito',
            name='licitacion_orden',
            field=models.CharField(blank=True, max_length=100, verbose_name='Licitación/Orden de compra'),
        ),
        migrations.AddField(
            model_name='remito',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemremito',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='itemremito',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones del ítem'),
        ),
        migrations.AlterField(
            model_name='itemremito',
            name='unidad_medida',
            field=models.CharField(default='UNIDAD', max_length=20, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='cliente',
            field=models.CharField(max_length=200, verbose_name='Cliente/Destinatario'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='remito',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='presupuesto_relacionado',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° de presupuesto'),
        ),
        migrations.CreateModel(
            name='RemitoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='remitos/adjuntos/%Y/%m/%d/', verbose_name='Archivo adjunto')),
                ('tipo', models.CharField(choices=[('foto', '🖼️ Fotos (mercadería, estado)'), ('documento', '📝 Documentos (facturas, recibos)'), ('comprobante', '🧾 Comprobantes de entrega'), ('firma', '✍️ Firmas (conformidad)'), ('otro', '📎 Otros')], default='otro', max_length=20, verbose_name='Tipo de archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('descripcion', models.TextField(blank=True, max_length=1000, verbose_name='Descripción')),
                ('tamaño', models.BigIntegerField(verbose_name='Tamaño en bytes')),
                ('extension', models.CharField(max_length=10, verbose_name='Extensión')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='remitos.remito', verbose_name='Remito relacionado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de remito',
                'verbose_name_plural': 'Adjuntos de remitos',
                'ordering': ['-fecha_subida', 'tipo'],
            },
        ),
        migrations.RemoveField(
            model_name='remito',
            name='referencia_externa',
        ),
        migrations.RemoveField(
            model_name='remito',
            name='serie',
        ),
    ]
