# Generated by Django 5.2.6 on 2025-12-10 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('remitos', '0002_alter_itemremito_options_alter_remito_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remitoadjunto',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Adjunto de remito', 'verbose_name_plural': 'Adjuntos de remito'},
        ),
        migrations.AlterField(
            model_name='remito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente/Destinatario'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='numero',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='remitoadjunto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='remitoadjunto',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='remitoadjunto',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='remitoadjunto',
            name='remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='remitos.remito'),
        ),
        migrations.AlterField(
            model_name='remitoadjunto',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remitoadjunto',
            name='tamaño',
            field=models.BigIntegerField(default=0, verbose_name='Tamaño en bytes'),
        ),
        migrations.AlterField(
            model_name='remitoadjunto',
            name='tipo',
            field=models.CharField(choices=[('entrega', '📦 Comprobante de entrega'), ('firma', '✍️ Firma del cliente'), ('foto', '🖼️ Foto del producto/servicio'), ('documento', '📄 Documentación adicional'), ('otro', '📎 Otros')], default='otro', max_length=20),
        ),
    ]
