# Generated by Django 5.2.6 on 2025-09-26 12:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('impuestos', '0001_initial'),
        ('marcas', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Código interno (se genera automáticamente si se deja vacío).', max_length=50, null=True, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/fotos/')),
                ('plano', models.FileField(blank=True, null=True, upload_to='productos/planos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categorias.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marcas.marca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor')),
            ],
            options={
                'ordering': ['sku', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='impuestos.impuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'unique_together': {('producto', 'impuesto', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='impuestos',
            field=models.ManyToManyField(blank=True, through='productos.ProductoImpuesto', to='impuestos.impuesto'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, help_text='Código interno (S00001...)', max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('costo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/imagenes/')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='servicios/adjuntos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categorias.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marcas.marca')),
            ],
            options={
                'ordering': ['codigo_interno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='impuestos.impuesto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='impuestos',
            field=models.ManyToManyField(blank=True, through='productos.ServicioImpuesto', to='impuestos.impuesto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku', 'codigo_barras'], name='productos_p_sku_938c41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicioimpuesto',
            unique_together={('servicio', 'impuesto', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['codigo_interno'], name='productos_s_codigo__fdc822_idx'),
        ),
    ]
