# Generated by Django 5.2.6 on 2026-04-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_servicio_costo_base_alter_servicio_precio_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_corta',
            field=models.CharField(blank=True, default='', help_text='Texto corto para tarjetas web.', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado_web',
            field=models.BooleanField(default=False, help_text='Indica si el producto aparece como destacado.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='mostrar_en_home',
            field=models.BooleanField(default=False, help_text='Indica si el producto aparece en la portada.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='orden_web',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la web.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='publicado_web',
            field=models.BooleanField(default=False, help_text='Indica si el producto puede mostrarse en la web.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug único para URL amigable.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_corta',
            field=models.CharField(blank=True, default='', help_text='Texto corto para tarjetas web.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicio',
            name='destacado_web',
            field=models.BooleanField(default=False, help_text='Indica si el servicio aparece como destacado.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='mostrar_en_home',
            field=models.BooleanField(default=False, help_text='Indica si el servicio aparece en la portada.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='orden_web',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la web.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='publicado_web',
            field=models.BooleanField(default=False, help_text='Indica si el servicio puede mostrarse en la web.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug único para URL amigable.', max_length=255, null=True, unique=True),
        ),
    ]
