# Generated by Django 5.2.6 on 2026-06-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_options_and_more'),
        ('productos', '0005_movimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='video',
            field=models.FileField(blank=True, help_text='Video demostrativo del producto. Puede incluir audio.', null=True, upload_to='productos/videos/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='video',
            field=models.FileField(blank=True, help_text='Video demostrativo del servicio. Puede incluir audio.', null=True, upload_to='servicios/videos/'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', 'creado'], name='productos_m_product_040c79_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['tipo'], name='productos_m_tipo_49bc3a_idx'),
        ),
    ]
