# Generated by Django 5.2.6 on 2026-06-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_video_servicio_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='plano',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='video',
        ),
    ]
