# Generated by Django 5.2.6 on 2025-09-26 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fisica', 'Persona Física'), ('juridica', 'Persona Jurídica')], default='fisica', max_length=10)),
                ('nombre', models.CharField(help_text='Nombre o Razón Social', max_length=200)),
                ('apellido', models.CharField(blank=True, help_text='Apellido (solo para Persona Física)', max_length=200, null=True)),
                ('documento', models.CharField(blank=True, help_text='DNI (8 dígitos) o CUIT (11 dígitos)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8,11}$', message='DNI/CUIT inválido')])),
                ('condicion_iva', models.CharField(choices=[('ri', 'Responsable Inscripto'), ('mono', 'Monotributista'), ('exento', 'Exento'), ('cf', 'Consumidor Final'), ('noresidente', 'No Residente')], default='cf', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['documento'], name='clientes_cl_documen_76f212_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('documento__regex', '^\\d{8}$'), ('documento__regex', '^\\d{11}$'), ('documento__isnull', True), _connector='OR'), name='cliente_valid_documento'), models.CheckConstraint(condition=models.Q(models.Q(('apellido__isnull', False), ('tipo', 'fisica')), ('tipo', 'juridica'), _connector='OR'), name='cliente_apellido_required_for_fisica')],
            },
        ),
    ]
