# Generated by Django 5.2.6 on 2026-07-25 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plazo_cobro_dias',
            field=models.PositiveIntegerField(default=0, help_text='Plazo predeterminado sugerido para nuevas facturas de cobranza.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
