# Generated by Django 5.2.6 on 2026-06-02 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Archivo',
                'verbose_name_plural': 'Tipos de Archivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='archivos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='archivos/thumbnails/')),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('extension', models.CharField(blank=True, editable=False, max_length=20)),
                ('tamano_bytes', models.BigIntegerField(default=0, editable=False)),
                ('checksum', models.CharField(blank=True, editable=False, help_text='SHA256', max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='archivos.tipoarchivo')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rol', models.CharField(choices=[('principal', 'Principal'), ('secundaria', 'Secundaria'), ('galeria', 'Galería'), ('manual', 'Manual'), ('plano', 'Plano'), ('video', 'Video'), ('adjunto', 'Adjunto'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='archivos.archivo')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Relación de Archivo',
                'verbose_name_plural': 'Relaciones de Archivos',
                'ordering': ['orden', '-creado'],
                'unique_together': {('content_type', 'object_id', 'archivo')},
            },
        ),
    ]
