# Generated by Django 5.2.6 on 2026-06-03 15:01

import archivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_archivo_activo_archivo_nombre_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoarchivo',
            name='carpeta',
            field=models.SlugField(blank=True, help_text='Carpeta física donde se almacenarán los archivos de este tipo.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=archivos.models.archivo_upload_path),
        ),
    ]
